spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/visionnotedb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100   # fetch join ??
